[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_core = "0.16.0"
serde = "1.0.189"
serde_json = "1.0.107"
tokio = { version = "1", features = ["full"] }
